// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgG1VjeYbIZngfuCBDI-x_l2GPTuPPOIE',
    appId: '1:197300811067:web:ca777ca15f6f162a86331e',
    messagingSenderId: '197300811067',
    projectId: 'pushnotification-e57f5',
    authDomain: 'pushnotification-e57f5.firebaseapp.com',
    storageBucket: 'pushnotification-e57f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa_s9g-MUBr56CgpCTN6OK2YFWcH0Ly6k',
    appId: '1:197300811067:android:6bdfcadfcca7a12c86331e',
    messagingSenderId: '197300811067',
    projectId: 'pushnotification-e57f5',
    storageBucket: 'pushnotification-e57f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPPlrtce8_F__VPAeLs9s3yVVQ900vGhQ',
    appId: '1:197300811067:ios:7f3e98601ce7fbf686331e',
    messagingSenderId: '197300811067',
    projectId: 'pushnotification-e57f5',
    storageBucket: 'pushnotification-e57f5.appspot.com',
    iosBundleId: 'com.example.batteryLow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPPlrtce8_F__VPAeLs9s3yVVQ900vGhQ',
    appId: '1:197300811067:ios:7f3e98601ce7fbf686331e',
    messagingSenderId: '197300811067',
    projectId: 'pushnotification-e57f5',
    storageBucket: 'pushnotification-e57f5.appspot.com',
    iosBundleId: 'com.example.batteryLow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgG1VjeYbIZngfuCBDI-x_l2GPTuPPOIE',
    appId: '1:197300811067:web:be49931542907d4e86331e',
    messagingSenderId: '197300811067',
    projectId: 'pushnotification-e57f5',
    authDomain: 'pushnotification-e57f5.firebaseapp.com',
    storageBucket: 'pushnotification-e57f5.appspot.com',
  );
}
